Update of epidict package to include an EWAR/EBS template
R4EPI/msfdict pull request #22
Opened 2023-02-20 19:14 UTC by pbkeating

I've updated the epidict package so that it creates a minimal fake dataset to run the EWAR/EBS template in the sitrep package.
Possible to review and incorporate?

2025-03-05 14:51 UTC, aspina7 requested changes
thanks pat comments for things that need addressing before merge

2025-03-05 14:51 UTC, aspina7 commented on R/msf_dict.R
> +#'    "Vaccination_short" (only used in surveys if `template = TRUE`) and "ebs
here you have put it under surveys

2025-03-05 14:51 UTC, aspina7 commented on R/msf_dict.R
> +    stop("disease must be one of 'Cholera', 'Measles', 'Meningitis', 'AJS' or 'ebs'", call. = FALSE)
here its under outbreaks

2025-03-05 14:51 UTC, aspina7 commented on R/msf_dict_rename_helper.R
> +#' "Vaccination_long" or "EWAR") `varnames` needs to be "name"`. Otherwise if using
here you have used a different name

2025-03-05 14:51 UTC, aspina7 commented on R/gen_msf_data.R
> +    dis_output$initials <- stringi::stri_rand_strings(nrow(dis_output), 2,
instead of stringi please use base as below - this way less dependencies and less problems for me to fix going forward 
`
replicate(nrow(dis_output), paste0(sample(letters, 2, replace = TRUE), collapse = ""))`

2025-03-05 14:51 UTC, aspina7 commented on R/gen_msf_data.R
> +    dis_output[dis_output$alert_status == 0, 42:49] <- NA
please write out var names (below too) - this is not a safe way of ensuring this selects correct columns going forward

2025-03-06 06:18 UTC, pbkeating commented on R/gen_msf_data.R
> +    dis_output[dis_output$alert_status == 0, 42:49] <- NA
Should I mention all of them, or just the start name and end name?

2025-03-06 06:26 UTC, aspina7 commented on R/gen_msf_data.R
> +    dis_output[dis_output$alert_status == 0, 42:49] <- NA
would say ideally just list all of them - then we dont end up in a headache down the line where the dataset changes order and we need to scratch our heads figuring out which variables we meant to use

2025-03-06 07:23 UTC, aspina7 commented on R/gen_msf_data.R
> +    dis_output[dis_output$alert_status == 0, 42:49] <- NA
ah actually just realised how many variabels that is - you know what just leave it and we can deal with the fallout...

2025-03-06 07:42 UTC, pbkeating commented
Only 8 columns, I’m fine to add them.
Thoughts?
P

Patrick Keating (he/him)
Epidemiology Advisor for Bangladesh, Ethiopia, India, South Sudan and Malaysia
Doctors Without Borders/Médecins Sans Frontières  (MSF UK)
Level 5, Artesian, 9 Prescot Street, London E1 8AZ
Whatsapp: +447871642307

Learn more about Applying Epidemiology in Humanitarian contexts on this Tembo course https://tembo.msf.org/course/view.php?id=3866

Find surveillance-related resources in the Surveillance toolkit<https://msfintl.sharepoint.com/:f:/s/OCA-dept-PHD/ElW2YbccjwxBniRuzHewBCYBAZ0ZpuWs7hI6ZeHMhv8DfA?e=Twz68W>

Find outbreak-related resources in the https://msfintl.sharepoint.com/sites/OCA-dept-PHD/SitePages/OMT-Page.aspx<https://msfintl.sharepoint.com/sites/OCA-dept-PHD/SitePages/OMT-Page.aspx#outbreak-reporting>


From: Alex Spina ***@***.***>
Sent: 06 March 2025 13:24
To: R4EPI/epidict ***@***.***>
Cc: Patrick Keating ***@***.***>; Author ***@***.***>
Subject: Re: [R4EPI/epidict] Update of epidict package to include an EWAR/EBS template (PR #22)


CAUTION: This email originated from outside MSF. Do not click links, open attachments or provide information unless you recognise the sender and know that the content is safe..

________________________________

@aspina7 commented on this pull request.

________________________________

In R/gen_msf_data.R<https://github.com/R4EPI/epidict/pull/22#discussion_r1982821302>:

> +    ## Add one person less for total under 5 identified by active case finding

+    dis_output$acf_under5 <- dis_output$acf_total - 1

+

+

+    ## Ensure that alert_status takes a value of 1 where risk characterisation

+    ## is y (yes)

+    dis_output$alert_status[dis_output$risk_characterisation == "y"] <- 1

+

+

+    ## Ensure that alert_status takes a value of 0 where risk characterisation

+    ## is n (n) or u (unsure)

+    dis_output$alert_status[dis_output$risk_characterisation == "n" |

+                              dis_output$risk_characterisation == "u"] <- 0

+

+    ## Convert all columns NA when no intervention required

+    dis_output[dis_output$alert_status == 0, 42:49] <- NA

ah actually just realised how many variabels that is - you know what just leave it and we can deal with the fallout...

—
Reply to this email directly, view it on GitHub<https://github.com/R4EPI/epidict/pull/22#discussion_r1982821302>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AE2NEQYUHG6M26V5EBENLJ32S7ZXLAVCNFSM6AAAAABWVROE4SVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDMNRTGU2TENZUG4>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2025-03-06 07:47 UTC, aspina7 commented
> Only 8 columns, I’m fine to add them. Thoughts? P

but the lines below have like 20 columns

2025-03-06 07:51 UTC, pbkeating commented
Oh, snap, nevermind!
P

Patrick Keating (he/him)
Epidemiology Advisor for Bangladesh, Ethiopia, India, South Sudan and Malaysia
Doctors Without Borders/Médecins Sans Frontières  (MSF UK)
Level 5, Artesian, 9 Prescot Street, London E1 8AZ
Whatsapp: +447871642307

Learn more about Applying Epidemiology in Humanitarian contexts on this Tembo course https://tembo.msf.org/course/view.php?id=3866

Find surveillance-related resources in the Surveillance toolkit<https://msfintl.sharepoint.com/:f:/s/OCA-dept-PHD/ElW2YbccjwxBniRuzHewBCYBAZ0ZpuWs7hI6ZeHMhv8DfA?e=Twz68W>

Find outbreak-related resources in the https://msfintl.sharepoint.com/sites/OCA-dept-PHD/SitePages/OMT-Page.aspx<https://msfintl.sharepoint.com/sites/OCA-dept-PHD/SitePages/OMT-Page.aspx#outbreak-reporting>


From: Alex Spina ***@***.***>
Sent: 06 March 2025 13:48
To: R4EPI/epidict ***@***.***>
Cc: Patrick Keating ***@***.***>; Author ***@***.***>
Subject: Re: [R4EPI/epidict] Update of epidict package to include an EWAR/EBS template (PR #22)


CAUTION: This email originated from outside MSF. Do not click links, open attachments or provide information unless you recognise the sender and know that the content is safe..

________________________________

Only 8 columns, I’m fine to add them. Thoughts? P

but the lines below have like 20 columns

—
Reply to this email directly, view it on GitHub<https://github.com/R4EPI/epidict/pull/22#issuecomment-2703065364>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AE2NEQ5F4B5MM2S3S3TYU232S74UBAVCNFSM6AAAAABWVROE4SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDOMBTGA3DKMZWGQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[Image removed by sender. aspina7]aspina7 left a comment (R4EPI/epidict#22)<https://github.com/R4EPI/epidict/pull/22#issuecomment-2703065364>

Only 8 columns, I’m fine to add them. Thoughts? P

but the lines below have like 20 columns

—
Reply to this email directly, view it on GitHub<https://github.com/R4EPI/epidict/pull/22#issuecomment-2703065364>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AE2NEQ5F4B5MM2S3S3TYU232S74UBAVCNFSM6AAAAABWVROE4SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDOMBTGA3DKMZWGQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2025-03-06 07:55 UTC, aspina7 commented
cool will clean up and merge - gracias 
also careful when you reply by email it includes your signature which posts your whatsapp number publically on the internet ye fool

2025-03-06 08:40 UTC, aspina7 approved these changes

2025-03-06 08:45 UTC, merged